### ISSUE TITLE
Are you training your own model or a pretrained model (Resnet18) ?

### ISSUE THREAD

**Issue by anwarghammam** [visinf/dense-ulearn-vos#11]
In the readme file you're training the data on resnet, what about your own model ? , Are you contributing in the data preprocessing level or you created your own framework.? If so, why it appears that you are training the data not with you own model(framework), but with the pretrained model (resnet)?

Thanks in advance.

**Comment by arnike** [comment]
Hi @anwarghammam,
I'm not sure what's causing the confusion. Our work describes an unsupervised procedure for training a backbone network (e.g. ResNet-18). This backbone network is initialised with random weights, i.e. from scratch.
Hope this answers your questions.
