### ISSUE TITLE
Train on custom video data

### ISSUE THREAD

**Issue by kail85** [visinf/dense-ulearn-vos#5]
What kind of preprocessing and preparation are required if I want to train from scratch on my own video data? Thanks

**Comment by arnike** [comment]
Hi @kail85,

there is no special pre-processing required. I would only ignore video frames with resolution lower than the crop size.

Best,
Nikita

**Comment by Poissonfish** [comment]
Hello @arnike,

I'm new to VOS problem and would like to know more details about how to train the custom video. The provided code:  
`bash ./launch/train.sh [ytvos|oxuva|track|kinetics]` doesn't seem to have an option for users to assign customized dataset. Did I miss anything here? Thank you for your help!

Best,
James
