### ISSUE TITLE
Request of the performance deviation when training with YouTube-VOS

### ISSUE THREAD

**Issue by JerryX1110** [visinf/dense-ulearn-vos#6]
Thanks for your great work! Could you provide the performance deviation when training with YouTube-VOS? By the way, I'd like to know whether the number reported in the paper is produced by the last training checkpoint or not. Thanks!

**Comment by JerryX1110** [comment]
Besides , I'd like to know training with which dataset produces the most stable performance. Thanks!

**Comment by JerryX1110** [comment]
I notice the deviation on YTB on your paper. And I'd like to know whether the number reported in the paper is produced by the last training checkpoint or not. Thanks!

**Comment by arnike** [comment]
Hi @JerryX1110,
thanks. We select the model based on 5 randomly chosen video sequences from DAVIS (please see Appendix B and the implementation). Those do tend to be the checkpoints later in the training.

Nikita

**Comment by JerryX1110** [comment]
Got that, thanks!
