### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by hushuai1** [visinf/dense-ulearn-vos#9]
the inference result is black

Available threads:  12
Loaded 2 sequences
Dataloader: filelists/val_ytvos2018_test  # 271
	 filelists/val_ytvos2018_test: no augmentation
Sequence 00 | 0062f687f1
>..........................................................................................<
Sequence 01 | 00f88c4f0a
>...................................................................................................................................................................................<
984.928 elapsed: Inference completed

![image](https://user-images.githubusercontent.com/43898397/156981151-572bc415-ec31-4a4e-9490-714e32e66286.png)

**Comment by arnike** [comment]
Hi  @hushuai1,
the **_vos** directory contains the inference result submittable to the evaluation server. Hence, the first segment will have greyscale value of 1, the second 2 and so on, so you won't see it. If you need visualisation, check out **_vis** directory (and make sure, ```VERBOSE``` is enabled in the inference code).
